[tool.black]
line-length = 78
exclude = 'migrations/'
target-version = ['py37']
[tool.isort]
profile= "hug"
line_length = 78
lines_after_imports = 2
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
combine_as_imports = true
